### ISSUE TITLE
Determine REST-API Endpoints and data structures

### ISSUE THREAD

**Issue by Laberbear** [OpServ-Monitoring/opserv-backend#1]
While these will most likely change in the future, a basic REST-API structure should be atleast documented.

Otherwise Frontend development could be stalled because of this.

**Comment by EndzeitBegins** [comment]
I'm on it.

**Comment by EndzeitBegins** [comment]
Changing any api url from /api to /apiref now redirects to the related (not yet existing) documentation entry on GitHub Pages.

I'll set up a documentation with Jekyll as soon as I've got the time.

**Comment by EndzeitBegins** [comment]
Jekyll is set up now, it's configuration however will most likely change in the future.

All documents including the rest api reference will be availabe under opserv.org/docs but most endpoints are not fully documented yet.

**Comment by EndzeitBegins** [comment]
All api endpoints scheduled for the initial release are implemented and listed in [the documentation](http://opserv.org/docs/apis/restful/data/v1/). 

We're working on the website and wiki right now. 
The individual articles in the documentation need to be enriched with more detailed information.

However, as maintaining the documentation is a continous process and frontend development may use the supplied list, this issue can be closed.
