### ISSUE TITLE
Evaluation of embedded databases

### ISSUE THREAD

**Issue by Laberbear** [OpServ-Monitoring/opserv-backend#12]
Vedis is pretty much out of the question now.

Here are some new Embedded DBs to evaluate:
https://github.com/adewes/blitzdb
https://github.com/seppo0010/rlite-py

**Comment by Laberbear** [comment]
http://www.zodb.org/en/latest/

**Comment by Laberbear** [comment]
http://buzhug.sourceforge.net/
http://www.methodsandtools.com/tools/codernitydb.php

**Comment by EndzeitBegins** [comment]
For some good reasons we will go with SQLite as embedded database solution for long time storage. The corresponding evaluation will be found in an additional paper. [german]
