### ISSUE TITLE
Decide on which embedded database to use

### ISSUE THREAD

**Issue by Laberbear** [OpServ-Monitoring/opserv-backend#2]
We could always go safe with SQLite, however I think vedis is the more clean solution to this.

**Comment by EndzeitBegins** [comment]
We'll go with [vedis](http://vedis.symisc.net/) and the [vedis-python](https://github.com/coleifer/vedis-python) library to avoid the effort and time needed to write own bindings.

In case vedis shouldn't fit our purposes or is no longer supported we still can fall back to sqlite or an other database.

**Comment by EndzeitBegins** [comment]
As Vedis turned out to be [no longer supported](https://github.com/coleifer/vedis-python/issues/9) we decided to use SQLite instead.
