### ISSUE TITLE
Setup Windows CI with Appveyor(?)

### ISSUE THREAD

**Issue by Laberbear** [OpServ-Monitoring/opserv-backend#4]
Doesn't have to Appveyor, however Windows will be one of the main platforms for this system, so usabe builds and testing are required.

**Comment by WereTheKidsFromAmerica** [comment]
Im on it thinking about a way to make a build that requires no compiler installed on the windows pc.

**Comment by EndzeitBegins** [comment]
Is there any progress or are the new insights regarding windows test/build support?

In addition, is building for FreeBSD planned as well?

**Comment by EndzeitBegins** [comment]
### CI status update

#### Windows

[AppVeyor](https://ci.appveyor.com/project/OpServ-Monitoring/opserv-backend/branch/master) has been set up to automate Windows builds, see cfc9aa7 and 25bbdd6.

Test coverage data is reported to [CodeClimate](https://codeclimate.com/github/OpServ-Monitoring/opserv-backend/coverage).

However deployment of bundled releases for Windows has not been set up yet!
____

#### OS X

[Travis CI](https://travis-ci.org/OpServ-Monitoring/opserv-backend) no longer builds on a Linux machine but on OS X from now on, see baea6f1. 
Builds are only run for Python v3.5

Test coverage data is reported to [Coveralls](https://coveralls.io/github/OpServ-Monitoring/opserv-backend?branch=master).

However deployment of bundled releases for OS X has not been set up yet!

____

#### Linux

As stated above Linux builds have been moved from Travis to [Semaphore CI](https://semaphoreci.com/opserv-monitoring-admin/opserv-backend).
Build are only run for Python v3.5

Test coverage data is reported to [Codacy](https://www.codacy.com/app/OpServ-Monitoring/opserv-backend/dashboard).

However deployment of bundled releases for Linux has not been set up yet!

**Comment by EndzeitBegins** [comment]
As just commented a Windows CI has been set up now, thus this issue can be closed.
