### ISSUE TITLE
Proper handling of CORS-Requsts in the REST-API

### ISSUE THREAD

**Issue by Laberbear** [OpServ-Monitoring/opserv-backend#5]
Until we plan the whole authorization part further, all requests should be authorized from a CORS point of view.

See:
http://www.davidadamojr.com/handling-cors-requests-in-flask-restful-apis/

**Comment by EndzeitBegins** [comment]
Implemented temporarily. [Commit e90b7934603e8d420beedd239b05b8380f01cfce](https://github.com/OpServ-Monitoring/opserv-backend/commit/e90b7934603e8d420beedd239b05b8380f01cfce)
