### ISSUE TITLE
Hosting the API 

### ISSUE THREAD

**Issue by WereTheKidsFromAmerica** [OpServ-Monitoring/opserv-backend#6]
I't  would be great to host the API in the web for CI purposes. Im feeling like a stress test and a documentation Test should be done every release.

**Comment by Laberbear** [comment]
Shouldn't this be done on the TravisCI testing platform?

**Comment by WereTheKidsFromAmerica** [comment]
Yes but for load testing on an api you still have to host it, since the capacity of travis etc. is limited
